### ISSUE TITLE
Score Screen ist nicht da bei Programstart

### ISSUE THREAD

**Issue by freaktech** [Darts4Home/Darts4Home-v1-public#10]
**Was ist das Problem, für das Du einen Verbesserungsvorschlag machen willst?**
Wenn man das Programm am Automat auf 2 Screens mit Autostart startet  bleibt der score Screen oben leer

**Welche Lösung möchtest Du vorschlagen?**
Es braucht ein Game Over Score Fenster welches bei Programmstart oben angezeigt wird.

**Alternative Vorschläge?**
Weiters ist dann die Frage was passiert nach Gameover oben nach Zeit X?

es soll dieses Bild (animation wieder kommen) und alternativ weitere Als Werbung

Programmordner:
d4h/modernui/startup/bild1.jpg
d4h/modernui/startup/bild2.jpg
der Reihe nach für 5 Sekunden, dann kann man auch Werbungen einblenden für Liga oder dergleichen.

sowie nach Spiel Ende oder nach wechsle Score Fenster auf   d4h/modernui/startup/
nach Zeit X

auch sollte ein Timeout wenn im Spiel 15 Minuten nichts mehr passiert ist, Spiel abbrechen
Wie in der Kneipe wenn wer einfach aufhört

**Comment by hoernertee** [comment]
Werbung hatten wir auf der todo. Idee war die Sponsoren als Bildschirms honer laufen zu lassen und online Sachen hochladen die dort dann aktualisiert werden. Z. B. Turnier Werbung oder sonstige Hinweise.

Aktuell könnte tatsächlich die Sponsoren Seite dort angezeigt werden.

**Comment by MarkusPiotrowski** [comment]
'AdvertiseScreen' ab Version 1.0.2.1. Videos und Bilder aus dem Ordner AdvertiseScreen werden abgespielt, wenn kein Spiel läuft.
