### ISSUE TITLE
No score nach Neustart des nächsten Legs. 

### ISSUE THREAD

**Issue by hoernertee** [Darts4Home/Darts4Home-v1-public#11]
**Was ist das Problem?**
X01 Bug: wenn ich 2 Player einstelle , mit 3 Sätzen , 3 Legs kommt ein Fehler sobald jedes leg vorbei ist und das nächste Leg gestartet werden soll. Dann kommt 2-3 mal Game On aber so Game -Game- Game On und dann sofort , No Score. Dann bleibt der Counter aber mit allen 3 Darts in Blau stehen , der Start Count steht auch auf 501 , 170 oder was ich auch einstelle. Wenn ich jetzt einen dart werfe wird nichts gezählt. Es geht erst weiter wenn ich auf den nächsten Gegner stelle , also Abdrücke. Und das jedem weiteren Neustart der legs. Habe den Matrix Converter 3.0 von Sven , braucht ihr noch mehr Infos ? Bestimmt welcher Treiber Version auf dem Converter ist. Da müsstet ihr mir aber nochmal sagen wie ich das auslese.

**Wann tritt der Fehler auf?**
x01, 2 Player, 3 Sets, 3 Legs

**Hard- und Software:**
 - Betriebssystem:
 - Darts4Home-Version: 1.0.2.0
 - Controller: MatrixConverter DB-Technics
 - ggf. Controller-Version: 3. 0
 - Dartboard:

![IMG_9921.jpg](https://github.com/Darts4Home/Darts4Home-v1-public/assets/63473672/fc175d39-a282-4401-bf5c-a54b82c5a9e1)

![IMG_9922.jpg](https://github.com/Darts4Home/Darts4Home-v1-public/assets/63473672/ec29f726-ba67-491c-bdab-ad38095b4dce)

![IMG_9923.jpg](https://github.com/Darts4Home/Darts4Home-v1-public/assets/63473672/f411d269-f358-4da4-a6ee-6a03ebd2da07)

![IMG_9924.jpg](https://github.com/Darts4Home/Darts4Home-v1-public/assets/63473672/816949a4-1ab6-4a34-bced-7f274d575a84)

![IMG_9925.jpg](https://github.com/Darts4Home/Darts4Home-v1-public/assets/63473672/c73f5459-bee6-48fc-bd1b-acc51be84574)

![IMG_9927.jpg](https://github.com/Darts4Home/Darts4Home-v1-public/assets/63473672/ca0a8462-caba-4c04-a44c-35a92032250a)

![IMG_9928.jpg](https://github.com/Darts4Home/Darts4Home-v1-public/assets/63473672/a11c89bf-cc30-4262-9255-4a0af1e33a5e)

**Comment by MarkusPiotrowski** [comment]
@Knutnoh Ich hab in Deinen letzten Commit ein Komentar hinterlassen (https://github.com/hoernertee/Darts4Home/commit/363be9e09d57cd216d9c6d016bdbe1ff9853de20#r119044174), ist eventuell der Grund dafür?

**Comment by hoernertee** [comment]
Habe geantwortet.
