### ISSUE TITLE
Spieler 1 gewinnt nicht bei einem Match X01

### ISSUE THREAD

**Issue by MarkusPiotrowski** [Darts4Home/Darts4Home-v1-public#14]
**Was ist das Problem?**
Wenn Spieler 1 die notwendigen Legs gewonnen hat, um das Spiel oder einen Satz zu beenden, passiert das nicht. Das Spiel geht einfach weiter. So kann Spieler 1 dann auch 3 oder 4 Legs gewinnen, selbst wenn das Spiel nur auf 2 Legs eingestellt ist. Bei Spieler 2 tritt das Problem nicht auf.

**Wann tritt der Fehler auf?**
Schritte, um den Fehler zu reproduzieren:
1. Wähle das Spiel X01/170
2. Stelle 2 Spieler und 2 Legs ein
3.  Lass den Spieler 1 zwei Legs gewinnen: Die Animation/Ansage für den Leggewinn kommt jedes Mal, aber nicht für den Satzgewinn oder den Spielgewinn

**Was sollte eigentlich passieren?**
Spieler 1 sollte das Spiel gewinnen...

**Screenshots**
![grafik](https://github.com/Darts4Home/Darts4Home-v1-public/assets/4503120/f410c5d4-1a43-48df-8267-49402c5fb4cb)

HIer hat Spieler 1 und Spiele 2 je 2 Legs gewonnen und damit eigentlich auch 2 Sets (Set war auf 1 Leg eingestellt):
![grafik](https://github.com/Darts4Home/Darts4Home-v1-public/assets/4503120/e2fd7d33-7fc2-4f92-b284-bf9bb5d6ff7d)

**Hard- und Software:**
 - Betriebssystem: Windows 10
 - Darts4Home-Version: [z.B. 1.0.2]
 - Controller: D4F

**Weitere Informationen**
Hat aber scheinbar nichts mit Issue #11 zu tun.

**Comment by Knutnoh** [comment]
gefixt
