### ISSUE TITLE
[Bug] Shooter-Rematch

### ISSUE THREAD

**Issue by Knutnoh** [Darts4Home/Darts4Home-v1-public#15]
**Was ist das Problem?**
Beim Rematch im Shooter Pro wird der Save Score nicht zurückgesetzt

**Wann tritt der Fehler auf?**
Rematch

**Was sollte eigentlich passieren?**
Save muss auf 0 gesetzt werden

**Comment by Knutnoh** [comment]
erledigt

**Comment by MarkusPiotrowski** [comment]
Noch nicht gemerged, sollte solange offen bleiben.

Hab das noch nicht ganz verstanden. Was muss ich machen, damit der Fehler auftritt? Zuerst Anfänger spielen und dann Pro? Oder gibt es bei Pro einen Save-Score?

**Comment by Knutnoh** [comment]
Einfach pro spielen mit 2 Spielern. Dann die Punktzahl 101 oder evtl. 201 werden. Dann wird der savescore angezeigt. Jetzt muss solange gespielt werden bis der gewonnen hat und danach Rematch starten. Hier kam dann immer das Problem auf, dass der savescore nicht auf 0 gesetzt wurde beim Rematch, sonder der aus der Vorrunde stehen geblieben ist

**Comment by MarkusPiotrowski** [comment]
Also bei Easy >= 101, 201, etc. und bei Pro, wenn genau 101, 201 etc. Warum wird bei Easy kein Save Score angezeigt?

**Comment by Knutnoh** [comment]
Hatten wir nicht drüber nachgedacht. Hat Tom aber auch schon angeregt. Kann ich mit einbauen

**Comment by MarkusPiotrowski** [comment]
Solved by [PR #119](https://github.com/hoernertee/Darts4Home/pull/119#issue-1783543926)
