### ISSUE TITLE
[Bug] Shooter easy Sound

### ISSUE THREAD

**Issue by Knutnoh** [Darts4Home/Darts4Home-v1-public#18]
**Was ist das Problem?**
Nachdem beim easy Shooter ein Spieler gesavet ist, ertönt bei jedem Treffer der savesound 

**Wann tritt der Fehler auf?**
Schritte, um den Fehler zu reproduzieren:
Spiele Shooter easy und werfe über 101

**Was sollte eigentlich passieren?**
Savesound soll nur einmalig gespielt werden, wenn man eine neue Saveebene erreicht hat

**Comment by MarkusPiotrowski** [comment]
Erledigt mit PR https://github.com/hoernertee/Darts4Home/pull/125

**Comment by MarkusPiotrowski** [comment]
Fehler ist doch noch da. 
- D4H starten
- Spiel Elimination Easy 170 mit 3 Spielern starten
- bei Spieler 1 ist alles OK
- bei Spieler 2 und 3 ertönt immer noch der Save-Sound bei jedem Wurf, sobald die erste Safe-Stufe (101) erreicht wurde
