### ISSUE TITLE
[Bug] Shooter easy Rematch 

### ISSUE THREAD

**Issue by Knutnoh** [Darts4Home/Darts4Home-v1-public#19]
**Was ist das Problem?**
Es wird beim Rematch die klassische x01 Rematch Reihenfolge gewählt, muss aber Reverse verwendet werden
**Wann tritt der Fehler auf?**
Schritte, um den Fehler zu reproduzieren:
1.Rematch bei Shooter easy 

**Was sollte eigentlich passieren?**
Der Spieler mit der höchsten Punktzahl muss als letztes dran sein beim Rematch

**Comment by MarkusPiotrowski** [comment]
Bei mir geht's:
1. D4H gestartet
2. Elimination 170 mit 3 Spielern gespielt:

<image src="https://github.com/Darts4Home/Darts4Home-v1-public/assets/4503120/6e0cfb0d-36e9-4f0d-83c5-5e9d6e0d9988" width=400>

Nach Rematch:
<image src="https://github.com/Darts4Home/Darts4Home-v1-public/assets/4503120/017207b0-8644-4f28-9cb7-a005fc0ee6de" width=400>


Vorher ein anderes Spiel gespielt? Ich hatte schon mal den Effekt, dass ich erst X01 gespielt habe und dann z.B. Cricket und da war die Sortierung auch verkehrt. Habe das aber noch nicht getestet.

**Comment by MarkusPiotrowski** [comment]
Kann den Fehler wie folgt reproduzieren:
1. Starte D4H
2. Drücke direkt auf "Spiel starten". Es startet ein 501-Spiel
3. Drücke "Cancel Game"
4. Starte ein Spiel Elimination Easy 170, 3 Spieler
5. Spiele das Spiel zu Ende, sodass Spieler 1 gewinnt und Spieler 2 den zweithöchsten Score hat
6. Drücke Rematch
7. Die Sortierung ist falsch (Spieler 1/2/3)

Irgendwas wird beim Abbruch des 501-Spiels nicht richtig zurückgesetzt.

**Comment by MarkusPiotrowski** [comment]
Das war ein allgemeiner Fehler, der immer auftrat, wenn man ein X01-Spiel abgebrochen hat. In 1.0.3 behoben.
