### ISSUE TITLE
[Verbesserung]
Home Taste

### ISSUE THREAD

**Issue by hoernertee** [Darts4Home/Darts4Home-v1-public#22]
Man kommt nur über viele Klicks zurück ins Hauptmenü wenn man die Spiele wechseln möchte. 

Eine Home Taste die ins Hauptmenü führt und in allen Fenstern global zu sehen ist. Vielleicht oben rechts bei den anderen Buttons? 

Zusätzlich einen shortcut auf der Tastatur? H für Home.

**Comment by MarkusPiotrowski** [comment]
In Version 1.0.3. Home-Button oben links
