### ISSUE TITLE
Korrektur wird im ScoreBoard nicht mit ausgeblendet

### ISSUE THREAD

**Issue by hoernertee** [Darts4Home/Darts4Home-v1-public#30]
Wenn man im Kiosk Bereich die Buttons im Scoreboard ausblendet dann bleibt der KorrekturButton weiterhin sichtbar.
Beim x01 getestet.

 - Darts4Home-Version: [z.B. 1.3.2]

![Scoreboard_002](https://github.com/Darts4Home/Darts4Home-v1-public/assets/63473672/cad6eec8-357f-443f-b317-46fec9004528)
![Scoreboard_001](https://github.com/Darts4Home/Darts4Home-v1-public/assets/63473672/18e20f62-410d-44e7-934c-ef2f40f13468)

**Comment by MarkusPiotrowski** [comment]
Schon lange behoben...
