### ISSUE TITLE
Definitioin des Power Buttons im Setup

### ISSUE THREAD

**Issue by freaktech** [Darts4Home/Darts4Home-v1-public#8]
**Was ist das Problem, für das Du einen Verbesserungsvorschlag machen willst?**
Da es verschiedenste Szenarien gibt wie die SW betrieben wird (Aufstellung in Verein, zuhause, Party mit Fremden)
ist es auch notwendig zu definieren was passiert wenn man Power Icon drückt.

Wenn das Gerät ohne Aufsicht steht darf man die APP nicht zumachen können sondern nur den PC runterfahren

**Welche Lösung möchtest Du vorschlagen?**
Im Setup ist die Einstellung nötig "Definition Powerbutten"

1. Power-Button überhaupt anzeigen JA/Nein
2. Power Button PW geschützt   Ja/Nein
3. 
wenn ja Funktion Powerbutton Auswahlfeld

4.  Was soll angezeigt werden
     A: "Nur App beenden"         , beim Drücken ...... "Pop Up kommt mit Frage "Wollen Sie das Programm beenden"
     B: "Nur PC runterfahren" , beim Drücken ...... "Pop Up kommt mit Frage "Wollen Sie das Programm beenden"
     C: " APP Beenden und PC Runterfahren"    Hier kommt dann ein Pop UP mit  Zwischenfrage ob man "Programm Beenden oder PC runterfahren will"

Somit kann ein Admin wenn er nur selbst am Gerät ist immer beides ohne PW laufen lassen.

Wenn man das Gerät im Club stehen hat oder auf Party, dann will ich nicht dass wer das Programm beenden kann und im WIN rumpfuschen kann.

Ziel:   Dart4 Home als Shell direkt starten wenn man PC einschaltet und nur Runterfahren auswählbar ohne PW.

**Comment by MarkusPiotrowski** [comment]
Hallo Tom,

danke für die Meldung, tatsächlich haben wir das schon auf dem Schirm. Meine Idee wäre, eine eigene Setup-Seite "Kiosk-Modus" o.ä. zu haben, wo gerade solche Einstellungen, die für Aufstellung oder Fremdnutzung relevant sind, eingestellt werden können: Einrichtung Münzzähler, Bildschirmgröße verändern, Runterfahren, Passwortschutz, maximale Rundenzahl für die Spiele, evt. auch Spiele deaktivieren(?), und was uns/Dir sonst noch so einfällt...

**Comment by MarkusPiotrowski** [comment]
Kommt mit dem nächsten Update:
![grafik](https://github.com/Darts4Home/Darts4Home-v1-public/assets/4503120/ff932a48-e7c8-4d4e-8595-a95ea040ad49)

**Comment by MarkusPiotrowski** [comment]
Optional einschaltbar (über "Zeige alle Optionen" oder "Bestätigen"):
![grafik](https://github.com/Darts4Home/Darts4Home-v1-public/assets/4503120/90370cdf-163b-4d41-8ee8-c30e62184c8f)

![grafik](https://github.com/Darts4Home/Darts4Home-v1-public/assets/4503120/542d25da-5000-4203-95eb-f2905d025c80)

**Comment by MarkusPiotrowski** [comment]
Mit https://github.com/hoernertee/Darts4Home/pull/118#issue-1775792407 implementiert.
Version 1.0.2.1
